package pedstore;

import Modelo.empleado;
import Modelo.hash;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.SqlEmpleado;

public class RegistrarUsuarios extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    ImageIcon icono = new ImageIcon("C:\\Users\\52557\\Desktop\\Promaskot\\Nueva Carpeta2\\PedStore\\src\\Imagenes\\LOGO1.png");
    

    public RegistrarUsuarios() {
        this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
        btnRegistrar.setEnabled(false);
        validar();
        impedirEscritura();

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtConContraseña = new javax.swing.JPasswordField();
        txtContraseña = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnRegistrarProducto = new javax.swing.JButton();
        lblApellidos = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblCContraseña = new javax.swing.JLabel();
        lblContraseña1 = new javax.swing.JLabel();
        lblCContraseña1 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        lblNombre = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        lblApeMaterno = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        cbxEstatus = new javax.swing.JComboBox<>();
        btnRegistrarProducto1 = new javax.swing.JButton();
        anio = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        dia = new javax.swing.JComboBox<>();
        anio1 = new javax.swing.JComboBox<>();
        mes1 = new javax.swing.JComboBox<>();
        dia1 = new javax.swing.JComboBox<>();
        btnGastos = new javax.swing.JButton();
        btnPromocion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });
        txtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPaternoKeyTyped(evt);
            }
        });

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });

        txtConContraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtConContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConContraseñaKeyReleased(evt);
            }
        });

        txtContraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyReleased(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Usu_Registrar.png"))); // NOI18N
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnvolver.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnRegistrarProducto.setText("Registrar producto");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        lblApellidos.setForeground(new java.awt.Color(255, 0, 0));
        lblApellidos.setText("*");

        lblCorreo.setForeground(new java.awt.Color(255, 0, 0));
        lblCorreo.setText("*");

        lblContraseña.setForeground(new java.awt.Color(255, 0, 0));
        lblContraseña.setText("*");

        lblCContraseña.setForeground(new java.awt.Color(255, 0, 0));
        lblCContraseña.setText("*");

        lblContraseña1.setForeground(new java.awt.Color(255, 0, 0));
        lblContraseña1.setText("*");

        lblCContraseña1.setForeground(new java.awt.Color(255, 0, 0));
        lblCContraseña1.setText("*");

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jCheckBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCheckBox2KeyTyped(evt);
            }
        });

        lblNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblNombre.setText("*");

        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });
        txtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMaternoKeyTyped(evt);
            }
        });

        lblApeMaterno.setForeground(new java.awt.Color(255, 0, 0));
        lblApeMaterno.setText("*");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        lblTelefono.setForeground(new java.awt.Color(255, 0, 0));
        lblTelefono.setText("*");

        txtFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaIngresoActionPerformed(evt);
            }
        });
        txtFechaIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaIngresoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaIngresoKeyTyped(evt);
            }
        });

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "USUARIO" }));

        cbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        btnRegistrarProducto1.setText("Registrar membresia");
        btnRegistrarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProducto1ActionPerformed(evt);
            }
        });

        anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        anio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        mes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        dia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        btnGastos.setText("GASTOS");
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });

        btnPromocion.setText("Promoción");
        btnPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblCContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(250, 250, 250)
                                        .addComponent(jCheckBox2)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidoPaterno)
                            .addComponent(txtApellidoMaterno)
                            .addComponent(txtNombre)
                            .addComponent(txtTelefono)
                            .addComponent(cbxTipo, 0, 326, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anio1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mes1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dia1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxEstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCorreo)
                            .addComponent(txtConContraseña)
                            .addComponent(txtContraseña)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRegistrarProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(btnPromocion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblApeMaterno))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidos)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(anio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(lblCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCContraseña)
                                .addComponent(lblCContraseña1))
                            .addComponent(txtConContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblContraseña)
                                .addComponent(lblContraseña1))
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btnRegistrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnVolver)))
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPromocion)
                        .addGap(18, 18, 18)
                        .addComponent(btnGastos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarProducto1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        regresar();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        SqlEmpleado modS = new SqlEmpleado();
        empleado mod = new empleado();

        String fecha = anio.getSelectedItem().toString() + "-" + mes.getSelectedItem().toString() + "-" + dia.getSelectedItem().toString();
        String fecha1 = anio1.getSelectedItem().toString() + "-" + mes1.getSelectedItem().toString() + "-" + dia1.getSelectedItem().toString();

        int i = JOptionPane.showConfirmDialog(this, "Deseas agregar al usuario: " + txtNombre.getText(), "ProMaskot", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, icono);
        if (i == 0) {
            String pass = new String(txtContraseña.getPassword());
            String passCon = new String(txtConContraseña.getPassword());
            try {
                if (txtNombre.getText().equals("") || txtApellidoPaterno.getText().equals("") || pass.equals("") || passCon.equals("") || txtCorreo.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Loa campos no estan llenos");
                } else {
                    if (pass.equals(passCon)) {

                        String nuevoPass = hash.sha1(pass);

                        //CONVERTIR ADMINISTRADOR =0 Y USUARIO=1
                        String e = cbxTipo.getSelectedItem().toString();
                        String estatus;
                        if (e.equals("ADMINISTRADOR")) {
                            estatus = "0";
                        } else {
                            estatus = "1";
                        }
                        //-------------------------------------------
                        mod.setNombre(txtNombre.getText());
                        mod.setApellidos(txtApellidoPaterno.getText() + " " + txtApellidoMaterno.getText());
                        mod.setFechaNacimiento(fecha);
                        mod.setCorreo(txtCorreo.getText());
                        mod.setTelefono(txtTelefono.getText());
                        mod.setTipoEmpleado(estatus);//checar esto
                        mod.setFechaIngreso(fecha1);
                        mod.setEstatus(cbxEstatus.getSelectedItem().toString());
                        mod.setContraseña(nuevoPass);

                        if (modS.registrar(mod)) {
                            JOptionPane.showConfirmDialog(this, "Se guardó el usuario " + txtNombre.getText(), "ProMaskot", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, icono);
                            limpiar();
                            regresar();
                        } else {
                            JOptionPane.showConfirmDialog(this, "No se guardo, escribiste algo mal ", "ProMaskot", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, icono);
                        }

                    } else {
                        JOptionPane.showConfirmDialog(this, "La contraseñas no coinciden", "ProMaskot", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, icono);
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showConfirmDialog(this, "Algo FALLÓ", "ProMaskot", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, icono);
            }
        } else {
            JOptionPane.showConfirmDialog(this, "No se pudo agregar al usuario", "ProMaskot", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, icono);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'A') | c > 'Z') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaternoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'A') | c > 'Z') {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoPaternoKeyTyped

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        validar();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaternoKeyReleased
        validar();
    }//GEN-LAST:event_txtApellidoPaternoKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        validar();
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyReleased
        validar();
    }//GEN-LAST:event_txtContraseñaKeyReleased

    private void txtConContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConContraseñaKeyReleased
        validar();
    }//GEN-LAST:event_txtConContraseñaKeyReleased

    private void jCheckBox2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox2KeyTyped

    }//GEN-LAST:event_jCheckBox2KeyTyped

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        impedirEscritura();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void txtApellidoMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaternoKeyReleased
        validar();
    }//GEN-LAST:event_txtApellidoMaternoKeyReleased

    private void txtApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaternoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'A') | c > 'Z') {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoMaternoKeyTyped

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        validar();
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        AgregarProducto ap = new AgregarProducto();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void btnRegistrarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProducto1ActionPerformed
        AgregarMembresia am = new AgregarMembresia();
        am.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistrarProducto1ActionPerformed

    private void txtFechaIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaIngresoKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < '-' || c > '-')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaIngresoKeyTyped

    private void txtFechaIngresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaIngresoKeyReleased
        validar();
    }//GEN-LAST:event_txtFechaIngresoKeyReleased

    private void txtFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaIngresoActionPerformed

    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
       Gastos g = new Gastos();
       g.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnGastosActionPerformed

    private void btnPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocionActionPerformed
        Promocion p = new Promocion();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPromocionActionPerformed
    private void limpiar() {
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtContraseña.setText("");
        txtCorreo.setText("");
        txtConContraseña.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anio;
    private javax.swing.JComboBox<String> anio1;
    private javax.swing.JButton btnGastos;
    private javax.swing.JButton btnPromocion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JButton btnRegistrarProducto1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxEstatus;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JComboBox<String> dia;
    private javax.swing.JComboBox<String> dia1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel lblApeMaterno;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCContraseña;
    private javax.swing.JLabel lblCContraseña1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblContraseña1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JComboBox<String> mes1;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JPasswordField txtConContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void regresar() {
        InicioAdmin i = new InicioAdmin();
        i.setVisible(true);
        dispose();
    }

    public void validar() {
        //Validar Nombre
        if (txtNombre.getText().isEmpty()) {
            lblNombre.setText("*");
        } else {
            lblNombre.setText("Listo");
        }

        //Validar apellidoPaterno
        if (txtApellidoPaterno.getText().isEmpty()) {
            lblApellidos.setText("*");
        } else {
            lblApellidos.setText("Listo");
        }

        //Validar apellidoMaterno
        if (txtApellidoMaterno.getText().isEmpty()) {
            lblApeMaterno.setText("*");
        } else {
            lblApeMaterno.setText("Listo");
        }

        //Telefono
        if (txtTelefono.getText().isEmpty()) {
            lblTelefono.setText("*");
        } else {
            lblTelefono.setText("Listo");
        }

        //Condicion para el correo
        if (txtCorreo.getText().isEmpty()) {
            lblCorreo.setText("*");
        } else if (!txtCorreo.getText().contains("@") || !txtCorreo.getText().contains(".com")) {
            lblCorreo.setText("*");
        } else {
            lblCorreo.setText("Listo");
        }

        //Condicion para contraseña
        if (txtContraseña.getText().isEmpty()) {
            lblContraseña.setText("*");
        } else if ((!txtContraseña.getText().contains("A") && !txtContraseña.getText().contains("B")&& !txtContraseña.getText().contains("L") && !txtContraseña.getText().contains("C") && !txtContraseña.getText().contains("D") && !txtConContraseña.getText().contains("E") && !txtContraseña.getText().contains("F") && !txtContraseña.getText().contains("G") && !txtContraseña.getText().contains("H")
                && !txtContraseña.getText().contains("I") && !txtContraseña.getText().contains("J") && !txtContraseña.getText().contains("K") && !txtContraseña.getText().contains("M") && !txtContraseña.getText().contains("N") && !txtContraseña.getText().contains("Ñ") && !txtContraseña.getText().contains("O") && !txtContraseña.getText().contains("P")
                && !txtContraseña.getText().contains("Q") && !txtContraseña.getText().contains("R") && !txtContraseña.getText().contains("S") && !txtContraseña.getText().contains("T") && !txtContraseña.getText().contains("U") && !txtContraseña.getText().contains("V") && !txtContraseña.getText().contains("X") && !txtContraseña.getText().contains("Y")
                && !txtContraseña.getText().contains("Z")) || (!txtContraseña.getText().contains("1") && !txtContraseña.getText().contains("2") && !txtContraseña.getText().contains("3") && !txtContraseña.getText().contains("4") && !txtContraseña.getText().contains("5") && !txtContraseña.getText().contains("6") && !txtContraseña.getText().contains("7")
                && !txtContraseña.getText().contains("8") && !txtContraseña.getText().contains("9") && !txtContraseña.getText().contains("10") && !txtContraseña.getText().contains("0"))) {
            lblContraseña.setText("*");
        } else {
            lblContraseña.setText("Listo");
        }

        //Confirmar Contraseña
        if (txtConContraseña.getText().isEmpty()) {
            lblCContraseña.setText("*");
        } else if ((!txtConContraseña.getText().contains("A") && !txtConContraseña.getText().contains("B")&& !txtContraseña.getText().contains("L") && !txtConContraseña.getText().contains("C") && !txtConContraseña.getText().contains("D") && !txtConContraseña.getText().contains("E") && !txtConContraseña.getText().contains("F") && !txtConContraseña.getText().contains("G") && !txtConContraseña.getText().contains("H")
                && !txtConContraseña.getText().contains("I") && !txtConContraseña.getText().contains("J") && !txtConContraseña.getText().contains("K") && !txtConContraseña.getText().contains("M") && !txtConContraseña.getText().contains("N") && !txtConContraseña.getText().contains("Ñ") && !txtConContraseña.getText().contains("O") && !txtConContraseña.getText().contains("P")
                && !txtConContraseña.getText().contains("Q") && !txtConContraseña.getText().contains("R") && !txtConContraseña.getText().contains("S") && !txtConContraseña.getText().contains("T") && !txtConContraseña.getText().contains("U") && !txtConContraseña.getText().contains("V") && !txtConContraseña.getText().contains("X") && !txtConContraseña.getText().contains("Y")
                && !txtConContraseña.getText().contains("Z")) || (!txtConContraseña.getText().contains("1") && !txtConContraseña.getText().contains("2") && !txtConContraseña.getText().contains("3") && !txtConContraseña.getText().contains("4") && !txtConContraseña.getText().contains("5") && !txtConContraseña.getText().contains("6") && !txtConContraseña.getText().contains("7")
                && !txtConContraseña.getText().contains("8") && !txtConContraseña.getText().contains("9") && !txtConContraseña.getText().contains("10") && !txtConContraseña.getText().contains("0"))) {
            lblCContraseña.setText("*");
        } else {
            lblCContraseña.setText("Listo");
        }

        if (txtContraseña.getText().equals(txtConContraseña.getText())) {
            lblCContraseña1.setText("");
            lblContraseña1.setText("");
        } else {
            lblCContraseña1.setText("Contraseñas no coinciden");
            lblContraseña1.setText("Contraseñas no coinciden");
        }

        //activar boton registrar
        if (txtNombre.getText().isEmpty() || txtApellidoPaterno.getText().isEmpty() || txtApellidoMaterno.getText().isEmpty() || /*txtFechaIngreso.getText().isEmpty() ||*/ txtTelefono.getText().isEmpty() /*|| txtFechaNacimiento.getText().isEmpty()*/ || txtFechaIngreso.getText().equals("*") || txtCorreo.getText().isEmpty() || txtContraseña.getText().isEmpty() || txtConContraseña.getText().isEmpty() || lblCorreo.getText().equals("*") || lblContraseña.getText().equals("*") || lblCContraseña.getText().equals("*")) {
            btnRegistrar.setEnabled(false);
        } else {
            btnRegistrar.setEnabled(true);
        }
    }

    public void impedirEscritura() {
        if (jCheckBox2.isSelected()) {
            txtNombre.setEditable(true);
            txtApellidoPaterno.setEditable(true);
            txtApellidoMaterno.setEditable(true);
           // txtFechaIngreso.setEditable(true);
            //  txtFechaNacimiento.setEditable(true);
            cbxEstatus.setEditable(true);
            cbxTipo.setEditable(true);
            txtTelefono.setEditable(true);
            txtConContraseña.setEditable(true);
            txtContraseña.setEditable(true);
            txtCorreo.setEditable(true);
            jCheckBox2.setEnabled(false);
        } else {
            txtNombre.setEditable(false);
            txtApellidoPaterno.setEditable(false);
            txtApellidoMaterno.setEditable(false);
           // txtFechaIngreso.setEditable(false);
            // txtFechaNacimiento.setEditable(false);
            cbxEstatus.setEditable(false);
            cbxTipo.setEditable(false);
            txtTelefono.setEditable(false);
            txtConContraseña.setEditable(false);
            txtContraseña.setEditable(false);
            txtCorreo.setEditable(false);
        }
    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/Registrar2.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
